name: Client CI/CD

env:
  CLIENT_BUCKET_NAME: "mern-todo-hosting"
  AWS_REGION: "us-east-1"

defaults:
  run:
    working-directory: client

on:
  push:
    branches:
      - ci

jobs:
  client_install_and_build:
    name: Install & Build Clinet
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache "node_modules" directory
        id: node_modules_cache_v1
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('package.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install app dependencies
        if: steps.node_modules_cache_v1.outputs.cache-hit != 'true'
        run: npm install

      - name: Test the App
        run: npm run test

      - name: Build the App
        run: npm run build

      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v1
        with:
          name: client-build
          path: client_build

  # deploy:
  #   runs-on: ubuntu-latest
  #   # When application is successfully tested and build has been generated
  #   # Then we can start with deployment
  #   needs: [client_test]
  #   steps:
  #     # Download previously shared build
  #     - name: Get artifact
  #       uses: actions/download-artifact@v1
  #       with:
  #         name: react-github-actions-build
  #     # Set the credentials from repository settings/secrets
  #     - name: Configure AWS credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  #     # Copy the files from build folder to the S3 bucket
  #     - name: Deploy to S3
  #       run: aws s3 sync . s3://react-github-actions --acl public-read
  #       working-directory: react-github-actions-build
